"""Run provenance recorder shared by all topics.

Every experiment run gets a directory ``<out_dir>/<timestamp>-<confighash>/`` containing
``run.json`` with enough metadata to reproduce or audit it. Raw outputs written into
``Run.dir`` are never edited afterwards; derived tables are regenerated by analysis scripts.
"""
from __future__ import annotations

import hashlib
import json
import os
import platform
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


def _git(*args: str) -> str:
    try:
        return subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL, text=True).strip()
    except Exception:  # noqa: BLE001 - provenance must never crash a run
        return ""


def _cpu_model() -> str:
    try:
        with open("/proc/cpuinfo", encoding="utf-8") as fh:
            for line in fh:
                if line.lower().startswith("model name"):
                    return line.split(":", 1)[1].strip()
    except OSError:
        pass
    return platform.processor() or "unknown"


def config_hash(config: dict[str, Any]) -> str:
    blob = json.dumps(config, sort_keys=True, default=str).encode()
    return hashlib.sha256(blob).hexdigest()[:12]


class Run:
    """Context manager that opens a run directory and records provenance."""

    def __init__(self, out_dir: str | os.PathLike[str], config: dict[str, Any], seed: int | None = None,
                 extra: dict[str, Any] | None = None) -> None:
        self.config = dict(config)
        self.seed = seed
        self.extra = extra or {}
        self.hash = config_hash(self.config)
        stamp = time.strftime("%Y%m%dT%H%M%S")
        self.dir = Path(out_dir) / f"{stamp}-{self.hash}"
        self.meta: dict[str, Any] = {}

    def __enter__(self) -> "Run":
        self.dir.mkdir(parents=True, exist_ok=False)
        self.meta = {
            "started": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "config": self.config,
            "config_hash": self.hash,
            "seed": self.seed,
            "git_commit": _git("rev-parse", "HEAD"),
            "git_dirty": bool(_git("status", "--porcelain")),
            "python": sys.version,
            "platform": platform.platform(),
            "kernel": platform.release(),
            "cpu": _cpu_model(),
            "argv": sys.argv,
            "extra": self.extra,
        }
        (self.dir / "run.json").write_text(json.dumps(self.meta, indent=2, default=str))
        return self

    def record(self, **fields: Any) -> None:
        """Add fields (for example engine versions) to run.json while the run is open."""
        self.meta.setdefault("recorded", {}).update(fields)
        (self.dir / "run.json").write_text(json.dumps(self.meta, indent=2, default=str))

    def __exit__(self, exc_type, exc, tb) -> None:
        self.meta["finished"] = time.strftime("%Y-%m-%dT%H:%M:%S%z")
        self.meta["status"] = "ok" if exc is None else f"error: {exc_type.__name__}: {exc}"
        (self.dir / "run.json").write_text(json.dumps(self.meta, indent=2, default=str))
